// Angular/crud-financial/crud/src/app/components/search/search.component.ts
import { Component, EventEmitter,OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss'],
})
export class SearchComponent implements OnInit {
  @Output() public emmitSearch: EventEmitter<string> = new EventEmitter();

  constructor() {}

  ngOnInit(): void {}

  searching(value: string) {
    this.emmitSearch.emit(value);
  }
}

<form>
  <img src="assets/search.svg" alt="lupa" />
  <input #input (keyup)="searching(input.value)" type="text" placeholder="Search..." />
</form>

// pokedex-react--rxjs/pokedex--rxjs/src/components/Search/index.tsx
import SearchIcon from "../../assets/search.svg";
import "./styles.scss";

function Search({ searchValue,onChangeCall }: SearchProps) {
  return (
    <section className="poke-search">
      <input
        className="poke-search__input"
        type="search"
        value={searchValue.value}
        onChange={onChangeCall}
      />
      <img src={SearchIcon} alt="lupa" />
    </section>
  );
}

export default Search;
